### ISSUE TITLE
关于 portal 的翻译

### ISSUE THREAD

**Issue by kiyonlin** [ng-docs/components#8]
目前`portal`被翻译成`门户`，个人感觉不直观，可能译作`传送`更贴切。`vue`用的是[teleport](https://v3.vuejs.org/guide/teleport.html#using-with-vue-components)，两者的功能是类似的。

**Comment by asnowwolf** [comment]
传送的词性不明确，而且不顺嘴，你觉得用传送点如何？

**Comment by kiyonlin** [comment]
赞同
